kind: pipeline
name: default

steps:
  - name: vet
    image: golang:1.11-stretch
    pull: always
    environment:
      DEP_VERSION: 0.5.0
      PACKAGE_NAME: terraform-provider-dfd
    commands:
      - ./.prep_drone.sh
      - go vet $PACKAGE_NAME
  - name: test
    image: golang:1.11-stretch
    pull: always
    commands:
      - ./.prep_drone.sh
      - go test -cover $PACKAGE_NAME
