[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "~0.11.10"

[[constraint]]
  name = "github.com/marqeta/go-dfd"
  version = "~0.0.2"

[prune]
  go-tests = true
  unused-packages = true
